server:
  port: 8080
spring:
  application:
    name: mercury
  devtools:
    add-properties: true
  main:
    profiles:
      active: dev
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: MYSQL
    show-sql: true
    generate-ddl: true
    properties:
      hibernate.id.new_generator_mappings: true
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: false
      hibernate.cache.region.factory_class: com.hazelcast.hibernate.HazelcastCacheRegionFactory
      hibernate.cache.hazelcast.instance_name:
      hibernate.cache.use_minimal_puts: true
      hibernate.cache.hazelcast.use_lite_member: true
      hibernate.enable_lazy_load_no_trans: true
    hibernate:
      ddl-auto: create
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  batch:
    job:
      enabled: false

datasource:
  readwrite:
    url: jdbc:mysql://localhost/db_books?useSSL=false&useLegacyDatetimeCode=false&serverTimeZone=UTC
    username: root
    password: adminadmin
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      data-source-properties:
        connectionTimeout: 30000
        minimumIdle: 5
        maximumPoolSize: 5
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true